#!/bin/bash

CPCMD="rsync -avL"

## Source Tree Location => jetpack 'data' location

$CPCMD deps/wmsy/lib/wmsy data/deps/

cfx --update-url=https://clicky.visophyte.org/files/labs/about-nosy/about-nosy.rdf --templatedir=xpi-template "$@"
